// <auto-generated />
using System;
using InglenookPuzzler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InglenookPuzzler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415121759_AddHeadshunt")]
    partial class AddHeadshunt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InglenookPuzzler.Models.Era", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eras");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Puzzle.PuzzleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoalState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<string>("StartState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PuzzleSessions");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Wagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("EraId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RollingStockNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("WagonTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.HasIndex("WagonTypeId");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.WagonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WagonTypes");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Puzzle.PuzzleSession", b =>
                {
                    b.OwnsOne("InglenookPuzzler.Models.Puzzle.PuzzleConfig", "Config", b1 =>
                        {
                            b1.Property<int>("PuzzleSessionId")
                                .HasColumnType("int");

                            b1.Property<int>("GoalWagons")
                                .HasColumnType("int");

                            b1.Property<int>("HeadshuntCapacity")
                                .HasColumnType("int");

                            b1.Property<bool>("TimedMode")
                                .HasColumnType("bit");

                            b1.Property<int>("TotalWagons")
                                .HasColumnType("int");

                            b1.Property<int>("TrackACapacity")
                                .HasColumnType("int");

                            b1.Property<int>("TrackBCapacity")
                                .HasColumnType("int");

                            b1.Property<int>("TrackCCapacity")
                                .HasColumnType("int");

                            b1.HasKey("PuzzleSessionId");

                            b1.ToTable("PuzzleSessions");

                            b1.WithOwner()
                                .HasForeignKey("PuzzleSessionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Wagon", b =>
                {
                    b.HasOne("InglenookPuzzler.Models.Era", "Era")
                        .WithMany("Wagons")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InglenookPuzzler.Models.WagonType", "WagonType")
                        .WithMany("Wagons")
                        .HasForeignKey("WagonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Era");

                    b.Navigation("WagonType");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Era", b =>
                {
                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.WagonType", b =>
                {
                    b.Navigation("Wagons");
                });
#pragma warning restore 612, 618
        }
    }
}
