// <auto-generated />
using System;
using InglenookPuzzler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InglenookPuzzler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("InglenookPuzzler.Models.Era", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eras");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Puzzle.PuzzleSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PuzzleSessions");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Wagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("RollingStockNumber")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("WagonTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EraId");

                    b.HasIndex("WagonTypeId");

                    b.ToTable("Wagons");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.WagonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WagonTypes");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Puzzle.PuzzleSession", b =>
                {
                    b.OwnsOne("InglenookPuzzler.Models.Puzzle.PuzzleConfig", "Config", b1 =>
                        {
                            b1.Property<int>("PuzzleSessionId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("GoalWagons")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("HeadshuntCapacity")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("TimedMode")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TotalWagons")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrackACapacity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrackBCapacity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TrackCCapacity")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PuzzleSessionId");

                            b1.ToTable("PuzzleSessions");

                            b1.WithOwner()
                                .HasForeignKey("PuzzleSessionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Wagon", b =>
                {
                    b.HasOne("InglenookPuzzler.Models.Era", "Era")
                        .WithMany("Wagons")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InglenookPuzzler.Models.WagonType", "WagonType")
                        .WithMany("Wagons")
                        .HasForeignKey("WagonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Era");

                    b.Navigation("WagonType");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.Era", b =>
                {
                    b.Navigation("Wagons");
                });

            modelBuilder.Entity("InglenookPuzzler.Models.WagonType", b =>
                {
                    b.Navigation("Wagons");
                });
#pragma warning restore 612, 618
        }
    }
}
